# Generated by Django 3.2.5 on 2021-08-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210806_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='size',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.ColorModel', verbose_name='color'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='products.SizeModel', verbose_name='size'),
        ),
    ]
