# Generated by Django 3.2.5 on 2021-08-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210811_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
    ]
