# Generated by Django 3.2.5 on 2021-08-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_wishlistmodel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={'verbose_name': 'wishlist', 'verbose_name_plural': 'wishlist'},
        ),
    ]
