# Generated by Django 3.2.5 on 2021-08-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_wishlistmodel_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistmodel',
            unique_together=set(),
        ),
    ]
